// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WaterControllerDbContext))]
    partial class WaterControllerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Measurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("device_id");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("intervalSeconds");

                    b.Property<int>("Pulses")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("pulses");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("measurements", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
