@Api_HostAddress = http://localhost:5271

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Api_HostAddress}}/api/measurements
Content-Type: application/json

{
  "device_id": "esp32-flow-01",
  "intervalSeconds": 1,
  "pulses_last_second": 42,
  "timestamp": 1786050000
}

###
