@Api_HostAddress = http://localhost:5271

###

POST {{Api_HostAddress}}/api/measurements
Content-Type: application/json

{
  "device_id": "esp32-flow-01",
  "intervalSeconds": 10,
  "pulses": 42,
  "timestamp": 1786050000
}

###

GET {{Api_HostAddress}}/api/consumption?range=24h&interval=1h
Accept: application/json

###

GET {{Api_HostAddress}}/api/consumption?range=7d&interval=1d&deviceId=ESP32_FLOW_METER_001
Accept: application/json

###
